name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1
    - name: Build
      run: msbuild /m /p:Configuration=Release  /p:Platform=x64 'rEFInd Boot Switch.sln'
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: rEFInd-boot-switch-Windows
        path: ${{github.workspace}}/x64/Release

  linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configure
      run: sudo apt install -y libefivar-dev
    - name: Build
      working-directory: rEFInd Boot Switch
      run: g++ 'rEFInd Boot Switch.cpp' -Wall -std=c++17 -lefivar -o 'rEFInd Boot Switch'
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: rEFInd-boot-switch-Linux
        path: ${{github.workspace}}/rEFInd Boot Switch
